### ISSUE TITLE
Add nightly or weekly build

### ISSUE THREAD

**Issue by nirs** [lima-vm/socket_vmnet#90]
The lima and qemu workflow may break when new lima or qemu becomes available in brew. The build and release worflow are simple but they may break when the macos image changes.

Add nightly or weekly scheduled run to detect regression eariler.

Example nightly build:

```yaml
on:
  schedule:
    - cron: '0 0 * * *'
```
